import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import os

load_dotenv()

ALERT_EMAIL = os.getenv("ALERT_EMAIL")
ALERT_PASSWORD = os.getenv("ALERT_PASSWORD")
ALERT_RECIPIENT = os.getenv("ALERT_RECIPIENT")

def send_anomaly_alert(buoy_id, timestamp, anomaly_score, sensor_data):
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"Ocean Anomaly Alert — Buoy {buoy_id}"
        msg["From"] = ALERT_EMAIL
        msg["To"] = ALERT_RECIPIENT

        html = f"""
        <html>
        <body style="font-family: sans-serif; background: #0a0f1e; color: #e0e0e0; padding: 24px;">
            <h2 style="color: #ff4757;">🌊 Ocean Anomaly Detected</h2>
            <table style="border-collapse: collapse; width: 100%;">
                <tr><td style="padding: 8px; color: #888;">Buoy ID</td><td style="padding: 8px; color: #00d4ff;">{buoy_id}</td></tr>
                <tr><td style="padding: 8px; color: #888;">Timestamp</td><td style="padding: 8px;">{timestamp}</td></tr>
                <tr><td style="padding: 8px; color: #888;">Anomaly Score</td><td style="padding: 8px; color: #ff4757;">{anomaly_score:.4f}</td></tr>
                <tr><td style="padding: 8px; color: #888;">Water Temp (WTMP)</td><td style="padding: 8px;">{sensor_data.get('WTMP', 'N/A')}</td></tr>
                <tr><td style="padding: 8px; color: #888;">Air Temp (ATMP)</td><td style="padding: 8px;">{sensor_data.get('ATMP', 'N/A')}</td></tr>
                <tr><td style="padding: 8px; color: #888;">Pressure (PRES)</td><td style="padding: 8px;">{sensor_data.get('PRES', 'N/A')}</td></tr>
                <tr><td style="padding: 8px; color: #888;">Wind Speed (WSPD)</td><td style="padding: 8px;">{sensor_data.get('WSPD', 'N/A')}</td></tr>
            </table>
            <p style="color: #888; margin-top: 24px;">This alert was generated by your Ocean Anomaly Detection System.</p>
        </body>
        </html>
        """

        msg.attach(MIMEText(html, "html"))

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(ALERT_EMAIL, ALERT_PASSWORD)
            server.sendmail(ALERT_EMAIL, ALERT_RECIPIENT, msg.as_string())

        print(f"Alert sent for buoy {buoy_id}!")
        return True

    except Exception as e:
        print(f"Failed to send alert: {e}")
        return False