version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: ocean_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: ocean_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - .:/app

  frontend:
    image: node:20-alpine
    container_name: ocean_frontend
    working_dir: /app
    volumes:
      - ../ocean-frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo_data: